blueprint:
  name: Zooz ZEN72 2.10 firmware
  description: Automations helper for the Zooz ZEN72 Dimmer Switch using the Zwave
    JS integration, on the 2.10 firmware.
  domain: automation
  input:
    zooz_ZEN77:
      name: Zooz ZEN72
      description: The ZEN72 Switch to interact with.
      selector:
        device:
          integration: zwave_js
          manufacturer: Zooz
          model: ZEN72
          multiple: false
    dimmer_up_1x:
      name: Top Paddle 1x
      description: 'Action to run on dimmer upper paddle single tap. Default: Turn
        on dimmer switch load to last/custom/full/max brightness.'
      default: []
      selector:
        action: {}
    dimmer_up_2x:
      name: Top Paddle 2x
      description: 'Action to run on dimmer upper paddle double tap. Default: Turn
        on dimmer switch to full/max/custom brightness.'
      default: []
      selector:
        action: {}
    dimmer_up_3x:
      name: Top Paddle 3x
      description: 'Action to run on dimmer upper paddle triple tap. Default: Enter
        inclusion/pairing mode.'
      default: []
      selector:
        action: {}
    dimmer_up_4x:
      name: Top Paddle 4x
      description: Action to run on dimmer upper paddle quadruple tap.
      default: []
      selector:
        action: {}
    dimmer_up_5x:
      name: Top Paddle 5x
      description: Action to run on dimmer upper paddle quintuple tap.
      default: []
      selector:
        action: {}
    dimmer_up_hold:
      name: Top Paddle Hold
      description: 'Action to run on dimmer upper paddle press-and-hold. Default:
        Increase dimmer brightness level.'
      default: []
      selector:
        action: {}
    dimmer_up_release:
      name: Top Paddle Release
      description: Action to run on dimmer upper paddle release.
      default: []
      selector:
        action: {}
    dimmer_down_1x:
      name: Lower Paddle 1x
      description: 'Action to run on dimmer lower paddle single tap. Default: Turn
        off dimmer switch load.'
      default: []
      selector:
        action: {}
    dimmer_down_2x:
      name: Lower Paddle 2x
      description: Action to run on dimmer lower paddle double tap.
      default: []
      selector:
        action: {}
    dimmer_down_3x:
      name: Lower Paddle 3x
      description: 'Action to run on dimmer lower paddle triple tap. Default: Enter
        exclusion/un-pairing mode.'
      default: []
      selector:
        action: {}
    dimmer_down_4x:
      name: Lower Paddle 4x
      description: Action to run on dimmer lower paddle quadruple tap.
      default: []
      selector:
        action: {}
    dimmer_down_5x:
      name: Lower Paddle 5x
      description: Action to run on dimmer lower paddle quintuple tap.
      default: []
      selector:
        action: {}
    dimmer_down_hold:
      name: Bottom Paddle Hold
      description: 'Action to run on dimmer lower paddle press-and-hold. Default:
        Decrease dimmer brightness level.'
      default: []
      selector:
        action: {}
    dimmer_down_release:
      name: Bottom Paddle Release
      description: Action to run on dimmer lower paddle double tap.
      default: []
      selector:
        action: {}
  source_url: https://community.home-assistant.io/t/zooz-ZEN77/322433
mode: queued
max_exceeded: silent
trigger:
- platform: event
  event_type: zwave_js_value_notification
  event_data:
    command_class_name: Central Scene
    device_id: !input zooz_ZEN72
action:
- variables:
    scene_id: '{{ trigger.event.data.label }}'
    attribute_id: '{{ trigger.event.data.value }}'
- choose:
  - conditions: '{{ scene_id == ''Scene 001'' }}'
    sequence:
    - choose:
      - conditions: '{{ attribute_id == 0 }}'
        sequence: !input dimmer_up_1x
      - conditions: '{{ attribute_id == 3 }}'
        sequence: !input dimmer_up_2x
      - conditions: '{{ attribute_id == 5 }}'
        sequence: !input dimmer_up_4x
      - conditions: '{{ attribute_id == 6 }}'
        sequence: !input dimmer_up_5x
      - conditions: '{{ attribute_id == 2 }}'
        sequence: !input dimmer_up_hold
      - conditions: '{{ attribute_id == 1 }}'
        sequence: !input dimmer_up_release
  - conditions: '{{ scene_id == ''Scene 002'' }}'
    sequence:
    - choose:
      - conditions: '{{ attribute_id == 0 }}'
        sequence: !input dimmer_down_1x
      - conditions: '{{ attribute_id == 3 }}'
        sequence: !input dimmer_down_2x
      - conditions: '{{ attribute_id == 5 }}'
        sequence: !input dimmer_down_4x
      - conditions: '{{ attribute_id == 6 }}'
        sequence: !input dimmer_down_5x
      - conditions: '{{ attribute_id == 2 }}'
        sequence: !input dimmer_down_hold
      - conditions: '{{ attribute_id == 1 }}'
        sequence: !input dimmer_down_release
